src/Entity/ApiClients.php
<?php

namespace App\Entity;

use App\Repository\ApiClientsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ApiClientsRepository::class)]
class ApiClients
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $client_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $client_secret = null;

    #[ORM\Column(length: 255)]
    private ?string $client_name = null;

    #[ORM\Column]
    private ?bool $_active = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $short_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $full_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo_url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $dpo = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $technical_contact = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $commercial_contact = null;

    #[ORM\OneToOne(mappedBy: 'apiclients_id', cascade: ['persist', 'remove'])]
    private ?ApiClientsGrants $apiClientsGrants = null;

    #[ORM\OneToOne(inversedBy: 'apiClients', cascade: ['persist', 'remove'])]
    private ?User $user_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?string
    {
        return $this->client_id;
    }

    public function setClientId(?string $client_id): self
    {
        $this->client_id = $client_id;

        return $this;
    }

    public function getClientSecret(): ?string
    {
        return $this->client_secret;
    }

    public function setClientSecret(?string $client_secret): self
    {
        $this->client_secret = $client_secret;

        return $this;
    }

    public function getClientName(): ?string
    {
        return $this->client_name;
    }

    public function setClientName(string $client_name): self
    {
        $this->client_name = $client_name;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->_active;
    }

    public function setActive(bool $_active): self
    {
        $this->_active = $_active;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getFullDescription(): ?string
    {
        return $this->full_description;
    }

    public function setFullDescription(?string $full_description): self
    {
        $this->full_description = $full_description;

        return $this;
    }

    public function getLogoUrl(): ?string
    {
        return $this->logo_url;
    }

    public function setLogoUrl(?string $logo_url): self
    {
        $this->logo_url = $logo_url;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getDpo(): ?string
    {
        return $this->dpo;
    }

    public function setDpo(?string $dpo): self
    {
        $this->dpo = $dpo;

        return $this;
    }

    public function getTechnicalContact(): ?string
    {
        return $this->technical_contact;
    }

    public function setTechnicalContact(?string $technical_contact): self
    {
        $this->technical_contact = $technical_contact;

        return $this;
    }

    public function getCommercialContact(): ?string
    {
        return $this->commercial_contact;
    }

    public function setCommercialContact(?string $commercial_contact): self
    {
        $this->commercial_contact = $commercial_contact;

        return $this;
    }

    public function getApiClientsGrants(): ?ApiClientsGrants
    {
        return $this->apiClientsGrants;
    }

    public function setApiClientsGrants(?ApiClientsGrants $apiClientsGrants): self
    {
        // unset the owning side of the relation if necessary
        if ($apiClientsGrants === null && $this->apiClientsGrants !== null) {
            $this->apiClientsGrants->setApiclientsId(null);
        }

        // set the owning side of the relation if necessary
        if ($apiClientsGrants !== null && $apiClientsGrants->getApiclientsId() !== $this) {
            $apiClientsGrants->setApiclientsId($this);
        }

        $this->apiClientsGrants = $apiClientsGrants;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Entity/Apiclients.php
<?php

namespace App\Entity;

use App\Repository\ApiclientsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ApiclientsRepository::class)]
class Apiclients
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    public ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $client_id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $client_secret = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $client_name = null;

    #[ORM\Column]
    private ?bool $active = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $short_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $full_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $logo_url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $dpo = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $technical_contact = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $commercial_contact = null;



    #[ORM\OneToOne(mappedBy: 'apiclients_id', cascade: ['persist', 'remove'])]
    private ?Apiclientsgrants $apiclientsgrants = null;

    #[ORM\ManyToOne(inversedBy: 'apiclients')]
    public ?user $user_id = null;

    #[ORM\OneToMany(mappedBy: 'apiclients_id', targetEntity: Structures::class)]
    public Collection $structures;

    public function __construct()
    {
        $this->structures = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClientId(): ?string
    {
        return $this->client_id;
    }

    public function setClientId(?string $client_id): self
    {
        $this->client_id = $client_id;

        return $this;
    }

    public function getClientSecret(): ?string
    {
        return $this->client_secret;
    }

    public function setClientSecret(?string $client_secret): self
    {
        $this->client_secret = $client_secret;

        return $this;
    }

    public function getClientName(): ?string
    {
        return $this->client_name;
    }

    public function setClientName(?string $client_name): self
    {
        $this->client_name = $client_name;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(?string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getFullDescription(): ?string
    {
        return $this->full_description;
    }

    public function setFullDescription(?string $full_description): self
    {
        $this->full_description = $full_description;

        return $this;
    }

    public function getLogoUrl(): ?string
    {
        return $this->logo_url;
    }

    public function setLogoUrl(?string $logo_url): self
    {
        $this->logo_url = $logo_url;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getDpo(): ?string
    {
        return $this->dpo;
    }

    public function setDpo(?string $dpo): self
    {
        $this->dpo = $dpo;

        return $this;
    }

    public function getTechnicalContact(): ?string
    {
        return $this->technical_contact;
    }

    public function setTechnicalContact(?string $technical_contact): self
    {
        $this->technical_contact = $technical_contact;

        return $this;
    }

    public function getCommercialContact(): ?string
    {
        return $this->commercial_contact;
    }

    public function setCommercialContact(?string $commercial_contact): self
    {
        $this->commercial_contact = $commercial_contact;

        return $this;
    }



    public function getApiclientsgrants(): ?Apiclientsgrants
    {
        return $this->apiclientsgrants;
    }

    public function setApiclientsgrants(?Apiclientsgrants $apiclientsgrants): self
    {
        // unset the owning side of the relation if necessary
        if ($apiclientsgrants === null && $this->apiclientsgrants !== null) {
            $this->apiclientsgrants->setApiclientsId(null);
        }

        // set the owning side of the relation if necessary
        if ($apiclientsgrants !== null && $apiclientsgrants->getApiclientsId() !== $this) {
            $apiclientsgrants->setApiclientsId($this);
        }

        $this->apiclientsgrants = $apiclientsgrants;

        return $this;
    }

    public function getUserId(): ?user
    {
        return $this->user_id;
    }

    public function setUserId(?user $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * @return Collection<int, Structures>
     */
    public function getStructures(): Collection
    {
        return $this->structures;
    }

    public function addStructure(Structures $structure): self
    {
        if (!$this->structures->contains($structure)) {
            $this->structures->add($structure);
            $structure->setApiclientsId($this);
        }

        return $this;
    }

    public function removeStructure(Structures $structure): self
    {
        if ($this->structures->removeElement($structure)) {
            // set the owning side to null (unless already changed)
            if ($structure->getApiclientsId() === $this) {
                $structure->setApiclientsId(null);
            }
        }

        return $this;
    }




}

src/Form/ApiclientsType.php
<?php

namespace App\Form;

use App\Entity\Apiclients;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ApiclientsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('client_id')
            ->add('client_secret')
            ->add('client_name')
            ->add('active')
            ->add('short_description')
            ->add('full_description')
            ->add('logo_url')
            ->add('url')
            ->add('dpo')
            ->add('technical_contact')
            ->add('commercial_contact')
            ->add('user_id')
            ->add('apiclientsgrants')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Apiclients::class,
        ]);
    }
}

src/Controller/ApiclientsController.php
<?php

namespace App\Controller;

use App\Entity\Apiclients;
use App\Form\ApiclientsType;
use App\Repository\ApiclientsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/apiclients')]
class ApiclientsController extends AbstractController
{
    #[Route('/', name: 'app_apiclients_index', methods: ['GET'])]
    public function index(ApiclientsRepository $apiclientsRepository): Response
    {
        return $this->render('apiclients/index.html.twig', [
            'apiclients' => $apiclientsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_apiclients_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ApiclientsRepository $apiclientsRepository): Response
    {
        $apiclient = new Apiclients();
        $form = $this->createForm(ApiclientsType::class, $apiclient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $apiclientsRepository->save($apiclient, true);

            return $this->redirectToRoute('app_apiclients_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('apiclients/new.html.twig', [
            'apiclient' => $apiclient,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_apiclients_show', methods: ['GET'])]
    public function show(Apiclients $apiclient): Response
    {
        return $this->render('apiclients/show.html.twig', [
            'apiclient' => $apiclient,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_apiclients_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Apiclients $apiclient, ApiclientsRepository $apiclientsRepository): Response
    {
        $form = $this->createForm(ApiclientsType::class, $apiclient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $apiclientsRepository->save($apiclient, true);

            return $this->redirectToRoute('app_apiclients_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('apiclients/edit.html.twig', [
            'apiclient' => $apiclient,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_apiclients_delete', methods: ['POST'])]
    public function delete(Request $request, Apiclients $apiclient, ApiclientsRepository $apiclientsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$apiclient->getId(), $request->request->get('_token'))) {
            $apiclientsRepository->remove($apiclient, true);
        }

        return $this->redirectToRoute('app_apiclients_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/apiclients/_delete_form.html.twig
<form method="post" action="{{ path('app_apiclients_delete', {'id': apiclient.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ apiclient.id) }}">
    <button class="btn">Delete</button>
</form>

templates/apiclients/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/apiclients/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Apiclients{% endblock %}

{% block body %}
    <h1>Edit Apiclients</h1>

    {{ include('apiclients/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_apiclients_index') }}">back to list</a>

    {{ include('apiclients/_delete_form.html.twig') }}
{% endblock %}

templates/apiclients/index.html.twig
{% extends ea.templatePath('layout') %}

{% block title %}Apiclients index{% endblock %}

  {% block stylesheets %}
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
      <link href="{{ asset('css/style.css') }}" type="text/css" rel="stylesheet">
      {{ encore_entry_link_tags('app') }}
  {% endblock %}



{% block body %}
    <h1 class="">Apiclients index</h1>

    <div class="container">
        <div class="row">
            <div class="col-6"> <label>Client_name</label><input type="search"></div>
            <div class="col-6"> <label>Client_id</label><input type="search"></div>
            <div class="col-3"><button type="button" class="btn btn-info w-25 ">actif</button></div>
            <div class="col-3"><button type="button" class="btn btn-info w-25 ">Inactif</button></div>
        </div>
        <div class="row">
            <div class="col-6">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>ClientId</th>
                        <th>ClientSecret</th>
                        <th>ClientName</th>
                        <th>Active</th>
                        <th>ShortDescription</th>
                        <th>FullDescription</th>
                        <th>Logo_url</th>
                        <th>Url</th>
                        <th>Dpo</th>
                        <th>Technical_contact</th>
                        <th>Commercial_contact</th>
                        <th>actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for apiclient in apiclients %}
                        <tr>
                            <td>{{ apiclient.id }}</td>
                            <td>{{ apiclient.clientId }}</td>
                            <td>{{ apiclient.clientSecret }}</td>
                            <td>{{ apiclient.clientName }}</td>
                            <td>{{ apiclient.active ? 'Yes' : 'No' }}</td>
                            <td>{{ apiclient.shortDescription }}</td>
                            <td>{{ apiclient.fullDescription }}</td>
                            <td>{{ apiclient.logoUrl }}</td>
                            <td>{{ apiclient.url }}</td>
                            <td>{{ apiclient.dpo }}</td>
                            <td>{{ apiclient.technicalContact }}</td>
                            <td>{{ apiclient.commercialContact }}</td>
                            <td>
                                <a href="{{ path('app_apiclients_show', {'id': apiclient.id}) }}">show</a>
                                <a href="{{ path('app_apiclients_edit', {'id': apiclient.id}) }}">edit</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="13">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>

        </div>


    </div>

    <a href="{{ path('app_apiclients_new') }}">Create new</a>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

{% endblock %}

templates/apiclients/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Apiclients{% endblock %}
{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="{{ asset('css/style.css') }}" type="text/css" rel="stylesheet">
    {{ encore_entry_link_tags('app') }}
{% endblock %}

{% block body %}
    <h1>Create new Apiclients</h1>

    {{ include('apiclients/_form.html.twig') }}

    <a href="{{ path('app_apiclients_index') }}">back to list</a>
{% endblock %}

templates/apiclients/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Apiclients{% endblock %}
{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="{{ asset('css/style.css') }}" type="text/css" rel="stylesheet">
    {{ encore_entry_link_tags('app') }}
{% endblock %}

{% block body %}
    <h1>Apiclients</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ apiclient.id }}</td>
            </tr>
            <tr>
                <th>Client_id</th>
                <td>{{ apiclient.clientId }}</td>
            </tr>
            <tr>
                <th>Client_secret</th>
                <td>{{ apiclient.clientSecret }}</td>
            </tr>
            <tr>
                <th>Client_name</th>
                <td>{{ apiclient.clientName }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ apiclient.active ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Short_description</th>
                <td>{{ apiclient.shortDescription }}</td>
            </tr>
            <tr>
                <th>Full_description</th>
                <td>{{ apiclient.fullDescription }}</td>
            </tr>
            <tr>
                <th>Logo_url</th>
                <td>{{ apiclient.logoUrl }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td>{{ apiclient.url }}</td>
            </tr>
            <tr>
                <th>Dpo</th>
                <td>{{ apiclient.dpo }}</td>
            </tr>
            <tr>
                <th>Technical_contact</th>
                <td>{{ apiclient.technicalContact }}</td>
            </tr>
            <tr>
                <th>Commercial_contact</th>
                <td>{{ apiclient.commercialContact }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_apiclients_index') }}">back to list</a>

    <a href="{{ path('app_apiclients_edit', {'id': apiclient.id}) }}">edit</a>

    {{ include('apiclients/_delete_form.html.twig') }}
{% endblock %}